version: "2"
      
networks:
  back:
    driver: bridge
    external: false

services:
  elasticsearch:
    image: elasticsearch:latest
    networks:
      - back
    expose:
      - "9200"
      - "9300"
  redis:
    image: redis:latest
    networks:
      - back
    expose:
      - "6379"
    command: redis-server --appendonly yes

  nle:
    image: beranger/nle:latest
    ports:
      - "3000:3000"
    networks:
      - back
      - default
    depends_on:
      - redis
      - elasticsearch

  nleadmin:
    image: beranger/nle-admin:latest
    ports:
      - "80:50759"
    networks:
      - default
    depends_on:
      - nle
    environment:
      - NLE_URL=192.168.99.100
      - NLE_PORT=3000
      - NLE_PROTOCOL=http
      - NLE_KEY=ee78363e-ddd3-41d4-bcfd-e1cb5984d879

